name: TTS Batch Synthesis

on:
  workflow_dispatch:

jobs:
  synthesize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run TTS batch script
        run: |
          python tts_batch.py

      - name: Archive mp3 results
        if: always()
        run: |
          if [ -d "output_mp3" ]; then
            zip -r mp3_results.zip output_mp3
          fi
          if [ -f "tts_batch.log" ]; then
            zip -g mp3_results.zip tts_batch.log
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mp3_results
          path: mp3_results.zip
