name: TTS Batch Synthesis

on:
  workflow_dispatch:

jobs:
  synthesize:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repo
        uses: actions/checkout@v4

      # Шаг 2: Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Установка ffmpeg
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # =====================================================================
      # ШАГ 5 (ИЗМЕНЕН): ДОБАВЛЕНЫ ECHO ДЛЯ ГАРАНТИРОВАННОГО ВЫВОДА
      # =====================================================================
      # Команды "echo" выводят текст немедленно и заставят GitHub
      # создать раскрывающийся лог.
      - name: Run TTS batch script
        run: |
          echo "--- Starting Python script now. Logs should appear below. ---"
          python -u tts_batch.py
          echo "--- Python script finished. ---"

      # Шаг 6: Архивирование MP3-файлов
      - name: Archive mp3 results
        if: always()
        run: |
          if [ -d "output_mp3" ]; then
            zip -r mp3_results.zip output_mp3
          fi

      # Шаг 7: Загрузка артефакта с MP3
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mp3_results
          path: mp3_results.zip

      # Шаг 8: Коммит и push лог-файла
      - name: Commit and push log file
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tts_batch.log
          if ! git diff --staged --quiet; then
            git commit -m "Update tts_batch.log with latest progress"
            git push
          else
            echo "No changes in log file to commit."
          fi
