name: TTS Batch Synthesis

on:
  workflow_dispatch:

jobs:
  synthesize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repo
        uses: actions/checkout@v4

      # Шаг 2: Диагностика (оставляем, он очень полезен)
      - name: Diagnose File State before script
        run: |
          echo "--- Checking if tts_batch.log exists BEFORE python script: ---"
          if [ -f "tts_batch.log" ]; then
            cat tts_batch.log | tail -n 5
          else
            echo "tts_batch.log does not exist yet."
          fi
          echo "--- End of initial diagnosis ---"

      # Шаг 3: Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 4: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 5: Установка ffmpeg
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Шаг 6: Запуск скрипта
      - name: Run TTS batch script
        run: |
          python -u tts_batch.py

      # Шаг 7: Упаковка артефакта
      - name: Archive mp3 results
        if: always()
        run: |
          if [ -d "output_mp3" ]; then
            zip -r mp3_results.zip output_mp3
          fi

      # Шаг 8: Загрузка артефакта
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mp3_results
          path: mp3_results.zip

      # Шаг 9: Сохранение лога
      - name: Commit and push log file
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # =====================================================================
          # КЛЮЧЕВОЕ ИСПРАВЛЕНИЕ:
          # Синхронизируемся с сервером ПРЯМО ПЕРЕД тем как делать коммит.
          # Это решает ошибку "rejected (fetch first)".
          # =====================================================================
          git pull
          
          git add -f tts_batch.log
          if ! git diff --staged --quiet; then
            git commit -m "Update tts_batch.log with latest progress"
            git push
          else
            echo "No changes in log file to commit."
          fi
