name: TTS Batch Synthesis

on:
  workflow_dispatch:

jobs:
  synthesize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repo
        uses: actions/checkout@v4

      # Шаг 2: Синхронизация с репозиторием
      - name: Sync with remote repository
        run: git pull

      # =====================================================================
      # ШАГ 2.5 (НОВЫЙ): ДИАГНОСТИКА СОСТОЯНИЯ ФАЙЛОВ
      # Этот шаг покажет нам, существует ли лог-файл и что в нем написано
      # ПЕРЕД тем, как Python-скрипт его прочитает.
      # =====================================================================
      - name: Diagnose File State
        run: |
          echo "--- Checking current directory contents: ---"
          ls -la
          echo "--- Checking if tts_batch.log exists and what's inside: ---"
          if [ -f "tts_batch.log" ]; then
            echo "tts_batch.log EXISTS. Printing contents:"
            cat tts_batch.log
          else
            echo "tts_batch.log DOES NOT EXIST at this stage."
          fi
          echo "--- End of diagnosis ---"

      # Шаг 3: Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 4: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 5: Установка ffmpeg
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Шаг 6: Запуск скрипта
      - name: Run TTS batch script
        run: |
          python -u tts_batch.py

      # Шаг 7: Упаковка артефакта
      - name: Archive mp3 results
        if: always()
        run: |
          if [ -d "output_mp3" ]; then
            zip -r mp3_results.zip output_mp3
          fi

      # Шаг 8: Загрузка артефакта
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mp3_results
          path: mp3_results.zip

      # Шаг 9: Сохранение лога
      - name: Commit and push log file
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f tts_batch.log
          if ! git diff --staged --quiet; then
            git commit -m "Update tts_batch.log with latest progress"
            git push
          else
            echo "No changes in log file to commit."
          fi
